name: flutter_icon_dynamic
description: "Change your Android and iOS app icon dynamically without any hassle!"
version: 0.0.2
homepage: https://github.com/sncf-connect-tech/flutter_icon_dynamic

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: sncf.connect.tech.flutter_icon_dynamic
        pluginClass: FlutterIconDynamicPlugin
      ios:
        pluginClass: FlutterIconDynamicPlugin
